# Generated by Django 4.1.5 on 2023-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_per_day",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
