# Generated by Django 4.1.5 on 2023-11-07 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
