# Generated by Django 4.1.5 on 2023-11-21 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_cart_cartitem_cart_products_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="password",
        ),
    ]
