# Generated by Django 4.1.5 on 2023-11-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_warehouse_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("website", models.URLField()),
                ("company_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
