# Generated by Django 4.1.5 on 2023-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_companyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
