# Generated by Django 4.1.5 on 2023-11-26 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
