# Generated by Django 4.1.5 on 2023-11-26 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_cart_cartitem_cart_products_cart_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
