# Generated by Django 4.1.5 on 2023-11-26 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_remove_product_company"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
