# Generated by Django 4.1.5 on 2023-12-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_order_orderitem_order_products_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.companyprofile",
            ),
        ),
    ]
