# Generated by Django 4.1.5 on 2023-12-03 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_product_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="company",
        ),
    ]
