# Generated by Django 4.1.5 on 2024-02-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_productbooking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbooking",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="productbooking",
            name="technician",
        ),
        migrations.AddField(
            model_name="productbooking",
            name="driver_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productbooking",
            name="technician_needed",
            field=models.BooleanField(default=False),
        ),
    ]
