# Generated by Django 4.1.5 on 2024-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_remove_productbooking_driver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbooking",
            name="product",
        ),
        migrations.AddField(
            model_name="productbooking",
            name="product_name",
            field=models.CharField(default="Default Product Name", max_length=100),
        ),
    ]
