# Generated by Django 4.1.5 on 2024-02-12 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_remove_productbooking_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productbooking",
            old_name="product_name",
            new_name="name",
        ),
    ]
